[project]
name = "sealer-ocr"
version = "0.1.0"
description = "Sealer result image ocr project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "opencv-python>=4.12.0.88",
    "pyinstaller>=6.17.0",
    "tqdm>=4.67.1",
]
